version: '3.4'

services:
  rabbit:
      image: rabbitmq:management
      hostname: rabbit
      ports:
          - "15672:15672"
      environment:
          - RABBITMQ_ERLANG_COOKIE='mysecret'
      networks:
        - barigui
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5

  barigui1.service:
    image: ${DOCKER_REGISTRY-}barigui1service
    build:
      context: .
      dockerfile: Barigui1.Service/Dockerfile
    networks:
        - barigui
    depends_on:
      - rabbit
    command: sh -c './wait-for rabbit:5672'
    restart: on-failure
      
  barigui2.service:
    image: ${DOCKER_REGISTRY-}barigui2service
    build:
      context: .
      dockerfile: Barigui2.Service/Dockerfile
    networks:
        - barigui
    depends_on:
      - rabbit
    command: sh -c './wait-for localhost:15672'
    restart: on-failure

networks:
    barigui:
      driver: bridge
